# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: film_development

test:
  <<: *default
  database: film_test

production:
  primary:
    <<: *default
    database: film_production
    username: film
    password: <%= ENV['FILM_DATABASE_PASSWORD'] %>
  cache:
    <<: *default
    database: film_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: film_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: film_production_cable
    migrations_paths: db/cable_migrate
